title: Projet
status:
  draft:
    label: Brouillon
  listed:
    label: Publié

columns:
  - width: 2/3
    sections:
      content:
        type: fields
        fields:
          type:
            label: Type de projet
            type: tags
            width: 1/2
            options: query
            query: site.children.template("project").pluck("type", ",", true)

          client:
            label: Client
            type: select
            options: query
            query: site.clients.split
            width: 1/2

          url:
            label: Url
            type: text
            width: 2/3

          color:
            label: Couleur
            type: colors
            width: 1/3

          description:
            label: Description
            type: textarea
            buttons: false

          galery:
            type: files
            label: Galerie
            info: '{{ file.dimensions }}'
            layout: cards

  - width: 1/3
    sections:
      sidebar:
        type: fields
        fields:
          cover:
            label: Image de couverture
            type: files
            max: 1
            layout: cards
            size: huge
            info: '{{ file.dimensions }}'
            multiple: false
            image:
              back: white

          videoCover:
            label: Video de couverture
            type: files
            max: 1
            layout: cards
            size: huge
            info: '{{ file.dimensions }}'
            multiple: false
            image:
              back: white

          releaseDate:
            label: Date de mise en ligne
            type: date
