title: Ivan Daum

columns:
  - width: 2/3
    sections:
      content:
        type: fields
        fields:
          about:
            label: À propos
            type: writer

          clients:
            type: tags
            label: Clients

          email:
            label: Email
            type: email

          social:
            label: Réseaux sociaux
            type: structure
            fields:
              name:
                label: Nom
                type: text
              url:
                label: Lien
                type: text

  - width: 1/3
    sections:
      projects: sections/projects
